apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-secrets.yaml
- mysql-release.yaml

generatorOptions:
 disableNameSuffixHash: true
 
configMapGenerator:
- name: mysql-values
  files:
  - values.yaml=mysql-values.yaml

configurations:
- kustomizeconfig.yaml
